// Avorelo generic adapter. Prompt-only fallback for unsupported or undetected AI tools.
// Writes a copy-ready prompt to .avorelo/prompt.md.

import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import type { AgentAdapter, AdapterDetection, AdapterInstallResult, AdapterUninstallResult, AdapterValidation } from "../adapter-interface.ts";

function buildPrompt(guidance?: string): string {
  const lines = [
    "# Avorelo — AI Work Control",
    "",
    "This project uses Avorelo for AI work control. Copy this into your AI tool's prompt.",
    "",
    "## Rules",
    "- Check `npx avorelo status` before starting work.",
    "- Run existing tests before declaring work complete.",
    "- Do not claim production readiness without Avorelo receipts.",
    "- Do not modify auth, billing, or migration files without explicit approval.",
    "- Stay within the declared task scope.",
  ];
  if (guidance) lines.push("", "## Session guidance", "", guidance);
  lines.push("", "---", "Generated by Avorelo. Run `npx avorelo prompt` to refresh.", "");
  return lines.join("\n");
}

export const genericAdapter: AgentAdapter = {
  id: "generic",
  displayName: "Generic (copy-ready prompt)",
  controlTier: "prompt-only",
  canInjectCorrection: false,
  canBlockAction: false,

  detect(_dir: string): AdapterDetection {
    return { detected: true, signals: ["Always available as fallback"], instructionSurface: null };
  },

  install(dir: string, guidance?: string): AdapterInstallResult {
    const promptPath = join(dir, ".avorelo", "prompt.md");
    try {
      mkdirSync(join(dir, ".avorelo"), { recursive: true });
      writeFileSync(promptPath, buildPrompt(guidance));
      return { installed: true, surfaces: [promptPath], warnings: [] };
    } catch (e) {
      return { installed: false, surfaces: [], warnings: [(e as Error).message] };
    }
  },

  uninstall(dir: string): AdapterUninstallResult {
    const promptPath = join(dir, ".avorelo", "prompt.md");
    if (existsSync(promptPath)) {
      try {
        const { unlinkSync } = require("node:fs");
        unlinkSync(promptPath);
        return { removed: [promptPath], preserved: [] };
      } catch {
        return { removed: [], preserved: [promptPath] };
      }
    }
    return { removed: [], preserved: [] };
  },

  validate(dir: string): AdapterValidation {
    const promptPath = join(dir, ".avorelo", "prompt.md");
    if (!existsSync(promptPath)) return { valid: false, issues: ["Prompt file not found"] };
    const content = readFileSync(promptPath, "utf8");
    if (!content.includes("Avorelo")) return { valid: false, issues: ["Prompt file missing Avorelo content"] };
    return { valid: true, issues: [] };
  },

  getInstructionSurface(dir: string): string | null {
    return join(dir, ".avorelo", "prompt.md");
  },
};
